version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./ShopGen.Server/Dockerfile
    env_file:
      - .env
    ports:
      - 8000:80
    depends_on:
      migrations:
          condition: service_completed_successfully
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=shopgen
    ports:
      - 5432:5432
    restart: "always"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
  migrations:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.Migrations
    env_file:
      - .env
    depends_on:
      - postgres
    entrypoint:
      - "bash"
      - "-c"
      - "dotnet ef database update --project ShopGen.Data --startup-project ShopGen.Server"

volumes:
  postgres_data: