version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./ShopGen.Server/Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      migrations:
          condition: service_completed_successfully
      redis:
        condition: service_started
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=shopgen
    ports:
      - 5432:5432
    restart: "always"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 2s
      retries: 3
  migrations:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.Migrations
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint:
      - "bash"
      - "-c"
      - "dotnet ef database update --project ShopGen.Data --startup-project ShopGen.Server"
  redis:
    image: redis:7.2.2
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
      - ./redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

volumes:
  postgres_data:
  redis_data: