version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./ShopGen.Server/Dockerfile
    env_file:
      - .env
    ports:
      - 8000:80
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=shopgen
    ports:
      - 5432:5432
    restart: "always"

volumes:
  postgres_data: