version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./shop_gen:/shop_gen
    env_file:
      - .env
    ports:
      - 8000:8000
    command: [ 'bash', '-c', 'gunicorn --bind :8000 --workers 4 --reload wsgi:application' ]
    depends_on:
      - postgres
      - initializer
  initializer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: [
      'bash',
      '-c',
      'python3 manage.py migrate && python3 manage.py runscript initializer'
    ]
    volumes:
      - ./shop_gen:/shop_gen
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=shopgen
    ports:
      - 5432:5432
    restart: "always"
  redis:
    image: redis:7.2.2
    read_only: true
    security_opt:
      - no-new-privileges:true
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
      - ./redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_settings worker -l INFO
    env_file:
      - .env
    # profiles:
    #   - dev
    depends_on:
      - redis
      - postgres
    volumes:
      - ./shop_gen:/shop_gen

volumes:
  postgres_data:
  redis_data: