webserverReplicaCount: 2
workersReplicaCount: 2

image:
  repository: harbor.star3.com/library/shop_gen
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8000

webserverResources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

workerResources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /ht
    port: http
readinessProbe:
  httpGet:
    path: /ht
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

loadbalancer:
  enabled: false
  hostname: "nicklesshopgen.com"
  name: "shopgen-balancer-1"
  certificate_id: "e3f652aa-7fb2-46d7-aa2c-a1612e850bb5"

ingress:
  enabled: true
  host: "shopgen.nicleary.com"



# Redis settings
redis:
  architecture: standalone
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 1