{{- if .Values.loadbalancer.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "shopgen.fullname" . }}-loadbalancer
  labels:
    {{- include "shopgen.common-labels" . | nindent 4 }}
  annotations:
    kubernetes.digitalocean.com/do-loadbalancer-name: "shopgen-balancer-1"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "1"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "e3f652aa-7fb2-46d7-aa2c-a1612e850bb5"
    service.beta.kubernetes.io/do-loadbalancer-hostname: {{ .Values.loadbalancer.hostname }}
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "shopgen.common-selectorLabels" . | nindent 4 }}
{{- end }}