FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ENV PATH $PATH:/root/.dotnet/tools
WORKDIR /src

# Install entity framework cli for migrations
RUN dotnet tool install --global dotnet-ef

COPY ShopGen.Data ShopGen.Data
COPY ShopGen.Server ShopGen.Server

RUN dotnet restore "./ShopGen.Server/ShopGen.Server.csproj"