FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ShopGen.Data ShopGen.Data
COPY ShopGen.Server ShopGen.Server
COPY ShopGen.Test ShopGen.Test

RUN dotnet restore "./ShopGen.Test/ShopGen.Test.csproj"

WORKDIR ./ShopGen.Test