name: "Main Action"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
jobs:
  test:
    # Runs pytest and black formatting tool
    runs-on: nicleary-ubuntu-k8s
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker build
        run: docker build -t shop_gen_test:${{ github.run_number }} -f Dockerfile.test .

      - name: Run tests
        run: docker run --name pytest shop_gen_test:${{ github.run_number }}

  build:
    runs-on: nicleary-ubuntu-k8s
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker build
        run: docker build -t shop_gen:${{ github.run_number }} -f Dockerfile .

      - name: Compress image
        run: docker save shop_gen:${{ github.run_number }} | gzip > shop_gen.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: compressed_image
          path: shop_gen.tar.gz

  trivy:
    needs: build
    runs-on: nicleary-ubuntu-k8s
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        name: Download image from artifact
        with:
          name: compressed_image

      - name: Load image from artifact
        run: docker load < shop_gen.tar.gz

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'shop_gen:${{ github.run_number }}'
          format: 'json'
          output: 'trivy-results.json'
          ignore-unfixed: true
      - name: Publish report
        id: import-scan
        uses: ivanamat/defectdojo-import-scan@v1
        with:
          token: ${{ secrets.DEFECTOJO_TOKEN }}
          defectdojo_url: ${{ secrets.DEFECTOJO_URL }}
          file: reports/trivy-scan-report.json
          scan_type: Trivy Scan
          engagement: 1